import type { Product, Review } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Classic White Sneakers",
    slug: "classic-white-sneakers",
    description: "Timeless white leather sneakers with premium comfort and style. Perfect for everyday wear.",
    price: 89.99,
    originalPrice: 129.99,
    category: "men",
    subcategory: "shoes",
    images: [
      "/white-leather-sneakers-product-photo.jpg",
      "/white-sneakers-side-view.jpg",
      "/white-sneakers-detail-shot.jpg",
    ],
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Off-White"],
    inStock: true,
    featured: true,
    new: false,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: "2",
    name: "Summer Floral Dress",
    slug: "summer-floral-dress",
    description: "Elegant floral print dress perfect for summer occasions. Lightweight and breathable fabric.",
    price: 79.99,
    category: "women",
    subcategory: "dresses",
    images: ["/floral-summer-dress-model.png", "/floral-dress-detail.jpg", "/floral-dress-back-view.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Print", "Navy Floral"],
    inStock: true,
    featured: true,
    new: true,
    rating: 4.8,
    reviewCount: 94,
  },
  {
    id: "3",
    name: "Leather Duffle Bag",
    slug: "leather-duffle-bag",
    description: "Premium leather duffle bag with spacious interior. Perfect for weekend getaways.",
    price: 199.99,
    originalPrice: 249.99,
    category: "accessories",
    subcategory: "bags",
    images: ["/brown-leather-duffle-bag.jpg", "/leather-bag-interior.jpg", "/duffle-bag-on-shoulder.jpg"],
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    inStock: true,
    featured: true,
    rating: 4.7,
    reviewCount: 56,
  },
  {
    id: "4",
    name: "Linen Button-Up Shirt",
    slug: "linen-button-up-shirt",
    description: "Breathable linen shirt with classic fit. Essential summer wardrobe piece.",
    price: 59.99,
    category: "men",
    subcategory: "t-shirts",
    images: ["/beige-linen-shirt-on-model.jpg", "/linen-shirt-detail.jpg", "/linen-shirt-folded.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Beige", "White", "Light Blue"],
    inStock: true,
    new: true,
    rating: 4.6,
    reviewCount: 73,
  },
  {
    id: "5",
    name: "Denim Jacket",
    slug: "denim-jacket",
    description: "Classic denim jacket with modern fit. A versatile piece for any season.",
    price: 119.99,
    category: "women",
    subcategory: "jackets",
    images: ["/blue-denim-jacket-on-model.jpg", "/denim-jacket-detail.png", "/denim-jacket-back.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Light Wash", "Dark Wash", "Black"],
    inStock: true,
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: "6",
    name: "Athletic Shorts",
    slug: "athletic-shorts",
    description: "Comfortable athletic shorts with moisture-wicking fabric. Perfect for workouts.",
    price: 39.99,
    category: "men",
    subcategory: "shorts",
    images: ["/black-athletic-shorts.jpg", "/athletic-shorts-on-model.jpg", "/shorts-detail.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Gray"],
    inStock: true,
    rating: 4.4,
    reviewCount: 89,
  },
  {
    id: "7",
    name: "Wool Blend Coat",
    slug: "wool-blend-coat",
    description: "Elegant wool blend coat for cold weather. Timeless design with modern tailoring.",
    price: 299.99,
    originalPrice: 399.99,
    category: "women",
    subcategory: "jackets",
    images: ["/camel-wool-coat-model.png", "/wool-coat-detail.jpg", "/coat-interior-lining.jpg"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Camel", "Black", "Navy"],
    inStock: true,
    featured: true,
    rating: 4.9,
    reviewCount: 67,
  },
  {
    id: "8",
    name: "Kids Cotton T-Shirt",
    slug: "kids-cotton-tshirt",
    description: "Soft cotton t-shirt for kids. Durable and comfortable for active play.",
    price: 19.99,
    category: "children",
    subcategory: "t-shirts",
    images: ["/colorful-kids-t-shirt.png", "/kids-shirt-on-child.jpg", "/placeholder.svg?height=600&width=600"],
    sizes: ["2T", "3T", "4T", "5T", "6", "7", "8"],
    colors: ["Red", "Blue", "Green", "Yellow"],
    inStock: true,
    new: true,
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: "9",
    name: "Slim Fit Chinos",
    slug: "slim-fit-chinos",
    description: "Modern slim fit chinos in premium cotton twill. Perfect for smart casual occasions.",
    price: 69.99,
    category: "men",
    subcategory: "shorts",
    images: ["/beige-chinos-on-model.jpg", "/chinos-detail.jpg", "/chinos-back-view.jpg"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Beige", "Navy", "Olive", "Black"],
    inStock: true,
    rating: 4.5,
    reviewCount: 45,
  },
  {
    id: "10",
    name: "Silk Blouse",
    slug: "silk-blouse",
    description: "Luxurious silk blouse with elegant draping. A sophisticated addition to any wardrobe.",
    price: 129.99,
    category: "women",
    subcategory: "t-shirts",
    images: ["/ivory-silk-blouse.jpg", "/silk-blouse-detail.jpg", "/silk-blouse-on-model.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Ivory", "Black", "Blush"],
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 82,
  },
  {
    id: "11",
    name: "Kids Denim Jeans",
    slug: "kids-denim-jeans",
    description: "Durable denim jeans for active kids. Comfortable stretch fabric with reinforced knees.",
    price: 34.99,
    category: "children",
    subcategory: "shorts",
    images: ["/kids-blue-jeans.jpg", "/kids-jeans-detail.jpg", "/child-wearing-jeans.jpg"],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8", "10", "12"],
    colors: ["Blue", "Black", "Light Wash"],
    inStock: true,
    rating: 4.6,
    reviewCount: 98,
  },
  {
    id: "12",
    name: "Leather Crossbody Bag",
    slug: "leather-crossbody-bag",
    description: "Compact leather crossbody bag with adjustable strap. Perfect for everyday essentials.",
    price: 89.99,
    category: "accessories",
    subcategory: "bags",
    images: ["/black-leather-crossbody-bag.jpg", "/crossbody-bag-interior.jpg", "/woman-wearing-crossbody-bag.jpg"],
    sizes: ["One Size"],
    colors: ["Black", "Brown", "Cognac"],
    inStock: true,
    new: true,
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: "13",
    name: "Merino Wool Sweater",
    slug: "merino-wool-sweater",
    description: "Premium merino wool sweater with classic crew neck. Soft, warm, and naturally breathable.",
    price: 149.99,
    category: "men",
    subcategory: "t-shirts",
    images: ["/navy-merino-wool-sweater.jpg", "/wool-sweater-texture.jpg", "/man-wearing-sweater.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Charcoal", "Burgundy", "Oatmeal"],
    inStock: true,
    featured: true,
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: "14",
    name: "Pleated Midi Skirt",
    slug: "pleated-midi-skirt",
    description: "Elegant pleated midi skirt in flowing fabric. Versatile piece for work or weekend.",
    price: 69.99,
    category: "women",
    subcategory: "dresses",
    images: ["/beige-pleated-midi-skirt.jpg", "/pleated-skirt-detail.jpg", "/woman-wearing-midi-skirt.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Beige", "Black", "Navy", "Olive"],
    inStock: true,
    rating: 4.7,
    reviewCount: 71,
  },
  {
    id: "15",
    name: "Kids Hooded Jacket",
    slug: "kids-hooded-jacket",
    description: "Water-resistant hooded jacket for kids. Lightweight and perfect for unpredictable weather.",
    price: 49.99,
    category: "children",
    subcategory: "jackets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8", "10"],
    colors: ["Navy", "Red", "Green", "Pink"],
    inStock: true,
    new: true,
    rating: 4.8,
    reviewCount: 103,
  },
  {
    id: "16",
    name: "Leather Belt",
    slug: "leather-belt",
    description: "Classic leather belt with polished buckle. Essential accessory for any wardrobe.",
    price: 39.99,
    category: "accessories",
    subcategory: "bags",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Black", "Tan"],
    inStock: true,
    rating: 4.5,
    reviewCount: 87,
  },
]

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "1",
    userName: "Sarah M.",
    rating: 5,
    comment: "These sneakers are incredibly comfortable! I wear them all day without any issues.",
    date: "2024-03-15",
    verified: true,
  },
  {
    id: "r2",
    productId: "1",
    userName: "Mike T.",
    rating: 4,
    comment: "Great quality and style. Runs slightly large, so consider sizing down.",
    date: "2024-03-10",
    verified: true,
  },
  {
    id: "r3",
    productId: "2",
    userName: "Emma L.",
    rating: 5,
    comment: "Absolutely love this dress! The fabric is beautiful and it fits perfectly.",
    date: "2024-03-20",
    verified: true,
  },
  {
    id: "r4",
    productId: "3",
    userName: "David R.",
    rating: 5,
    comment: "Excellent quality leather bag. Worth every penny!",
    date: "2024-03-18",
    verified: true,
  },
]

export const categories = [
  { id: "men", name: "Men's", slug: "men" },
  { id: "women", name: "Women's", slug: "women" },
  { id: "children", name: "Children's", slug: "children" },
  { id: "accessories", name: "Accessories", slug: "accessories" },
]

export const subcategories = [
  { id: "shoes", name: "Shoes", slug: "shoes" },
  { id: "dresses", name: "Dresses", slug: "dresses" },
  { id: "jackets", name: "Jackets", slug: "jackets" },
  { id: "shorts", name: "Shorts", slug: "shorts" },
  { id: "t-shirts", name: "T-Shirts", slug: "t-shirts" },
  { id: "bags", name: "Bags", slug: "bags" },
]
